/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimCheckBox: typeof import('./src/components/input/AnimCheckBox.vue')['default']
    AnimRadio: typeof import('./src/components/input/AnimRadio.vue')['default']
    ColorMapper: typeof import('./src/components/chart/ColorMapper.vue')['default']
    DragList: typeof import('./src/components/list/DragList.vue')['default']
    DropdownView: typeof import('./src/components/DropdownView.vue')['default']
    IconAdd: typeof import('./src/components/icon/IconAdd.vue')['default']
    IconDelete: typeof import('./src/components/icon/IconDelete.vue')['default']
    IconDrop: typeof import('./src/components/icon/IconDrop.vue')['default']
    IconMenu: typeof import('./src/components/icon/IconMenu.vue')['default']
    IconMinus: typeof import('./src/components/icon/IconMinus.vue')['default']
    IconShuffle: typeof import('./src/components/icon/IconShuffle.vue')['default']
    ImgDisplay: typeof import('./src/components/ImgDisplay.vue')['default']
    List: typeof import('./src/components/list/List.vue')['default']
    ListGroup: typeof import('./src/components/list/ListGroup.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NResult: typeof import('naive-ui')['NResult']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PieChart: typeof import('./src/components/chart/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SwitchNav: typeof import('./src/components/SwitchNav.vue')['default']
    TestView: typeof import('./src/components/TestView.vue')['default']
    VericationCode: typeof import('./src/components/VericationCode.vue')['default']
  }
}
